name:                callpass
version:             0.1.0.0
github:              "schrodingerzhu/callpass"
license:             BSD3
author:              "schrodinger"
maintainer:          "i@zhuyi.fan"
copyright:           "2019 schrodinger"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Language

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/schrodingerzhu/callpass#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.15.0.0 && < 1
- process >= 1.6.5.0

library:
  source-dirs: src

executables:
  gen-callgraph:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - callpass

tests:
  callpass-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - callpass
